
language: node_js
node_js:
  - "6.9"
  - "4.6"
install:
  - cd other_package
  - npm install && npm run build
  - cd ..
  - npm install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
